version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder
        user: builder
    resource_class: medium+

jobs:
  build:
    executor: aebuilder
    steps:
      - checkout
      - run: make test
