version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder:bionic-otp24
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-j2"
  aebuilder23:
    docker:
      - image: aeternity/builder:bionic-otp23
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-j2"

jobs:
  - otp24
      build:
        executor: aebuilder
        steps:
          - checkout
          - run: make test
          - store_artifacts:
              path: _build/test/logs
  - otp23
      build:
        executor: aebuilder23
        steps:
          - checkout
          - run: make test
          - store_artifacts:
              path: _build/test/logs
