version: 2.1

executors:
  aebuilder:
    parameters:
      otp:
        type: string
    docker:
      - image: aeternity/builder:focal-<< parameters.otp >>
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-j2"
      ERLANG_ROCKSDB_OPTS: "-DWITH_SYSTEM_ROCKSDB=ON -DWITH_SNAPPY=ON -DWITH_LZ4=ON -DWITH_BZ2=ON -DWITH_ZSTD=ON"


jobs:
  build_and_test:
    parameters:
      otp:
        type: string
    executor:
      name: aebuilder
      otp: << parameters.otp >>
    steps:
      - checkout
      - run: make test
      - store_artifacts:
          path: _build/test/logs

workflows:
  commit:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              otp: ["otp24", "otp25", "otp26"]
