version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder:bionic-otp23
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-j2"

jobs:
  build:
    executor: aebuilder
    steps:
      - checkout
      - run: make test
