version: 2.1

executors:
  aebuilder:
    docker:
      - image: aeternity/builder
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-DWITH_BUNDLE_LZ4=ON -j2"

jobs:
  build:
    executor: aebuilder
    steps:
      - checkout
      - run: make test
