version: 2.1

executors:
  aebuilder:
    parameters:
      otp:
        type: string
    docker:
      - image: aeternity/builder:bionic-<< parameters.otp >>
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-j2"

jobs:
  build_and_test:
    parameters:
      otp:
        type: string
    executor:
      name: aebuilder
      otp: << parameters.otp >>
    steps:
      - checkout
      - run: make test
      - store_artifacts:
          path: _build/test/logs

workflows:
  commit:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              otp: ["otp23", "otp24"]
