name: Run CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['23.3.4.18', '24.3.4.6', '25.1.2']
        rebar3: ['3.20.0']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: add cmake repo
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb https://apt.kitware.com/ubuntu/ $(lsb_release -c | awk '{print $2}') main
          repo-name: kitware
          keys-asc: https://apt.kitware.com/keys/kitware-archive-latest.asc
          packages-to-install: cmake-data cmake-curses-gui
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do dialyzer, xref, eunit, ct
