name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v3
    # install dependencies
    - name: install-cmake
      # You may pin to the exact commit or the version.
      # uses: Symbitic/install-cmake@301e932c0011b8d12d8bf33d4975fd1e17972709
      uses: Symbitic/install-cmake@v0.1.0
      with:
        # Version of CMake to install
        cmake: 3.17.2
        # Version of ninja-build to install
        ninja: 1.9.0
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do dialyzer, xref, eunit, ct
