name: Run CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['23.3.4.18', '24.3.4.6', '25.1.2']
        rebar3: ['3.20.0']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Setup cmake
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null ; \
          N=$(lsb_release -c | awk '{print $2}'); \
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ ${N} main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null ; \
          apt-get update ; \
          rm /usr/share/keyrings/kitware-archive-keyring.gpg ; \
          apt-get install -y kitware-archive-keyring ; \
          apt-get install -y cmake cmake-data cmake-curses-gui
      - name: Use cmake
        run: cmake --version
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do dialyzer, xref, eunit, ct
