name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v3
    # install dependencies
    - name: python3
      run: apt-get update && apt-get install -y python3 python3-pip
    - name: install-cmake
      # You may pin to the exact commit or the version.
      # uses: ssrobins/install-cmake@3822d84c7bbd0d435b866c6afb308060c843124e
      uses: ssrobins/install-cmake@v1
      #with:
      #  # CMake version in the form of 3.24.3 or 3.25.0-rc4 for release candidates
      #  version: # optional
      #  # Consider a release candidate when selecting the latest version
      #  release-candidate: # optional
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do dialyzer, xref, eunit, ct
